DROP TABLE IF EXISTS tar_tarefas;

DROP TABLE IF EXISTS usr_usuarios;

CREATE TABLE usr_usuarios (
  usr_id INT PRIMARY KEY AUTO_INCREMENT,
  usr_email VARCHAR(100) NOT NULL,
  usr_senha VARCHAR(100) NOT NULL
);
 
 
CREATE TABLE tar_tarefas (
  tar_ID INT PRIMARY KEY AUTO_INCREMENT,
  tar_TITULO VARCHAR(50) NOT NULL,
  tar_DESCRICAO VARCHAR(100) DEFAULT NULL,
  tar_DATA_EXPIRACAO DATE NOT NULL,
  tar_CONCLUIDA BIT DEFAULT FALSE,
  usr_id INT NOT NULL,
  CONSTRAINT FK_TAREFAS_USUARIOS FOREIGN KEY (usr_id) REFERENCES usr_usuarios (usr_id)
);
 
